tinymce.addI18n('es_TDI',{
    "Add to Dictionary" : "A\u00f1adir al Diccionario",
    "Advanced" : "Avanzado",
    "Align center" : "Alinear al Centro",
    "Align left" : "Alinear a Izquierda",
    "Align right" : "Alinear a Derecha",
    "Alignment" : "Alineaci\u00f3n",
    "Alternative source" : "Enlace alternativo",
    "Anchor" : "Ancla",
    "Anchors" : "Anclas",
    "Apply" : "Aplicar",
    "Author" : "Autor",
    "Back" : "Atr\u00e1s",
    "Background color" : "Color de fondo",
    "B" : "B",
    "Blockquote" : "Bloque de cita",
    "Blocks" : "Bloques",
    "Body" : "Cuerpo",
    "Bold" : "Negrita",
    "Border color" : "Color del borde",
    "Border" : "Borde",
    "Bottom" : "Abajo",
    "Brightness" : "Brillo",
    "Bullet list" : "Lista de Vi\u00f1etas",
    "Cancel" : "Cancelar",
    "Caption" : "Subt\u00edtulo",
    "Cell padding" : "Relleno de celda",
    "Cell properties" : "Propiedades de la celda",
    "Cell spacing" : "Espacio entre celdas",
    "Cell type" : "Tipo de celda",
    "Cell" : "Celda",
    "Center" : "Centrado",
    "Circle" : "C\u00edrculo",
    "Clear formatting" : "Limpiar formato",
    "Close" : "Cerrar",
    "Code" : "C\u00f3digo",
    "Color levels" : "Niveles de color",
    "Color" : "Color",
    "Cols" : "Columnas",
    "Column group" : "Grupo de columnas",
    "Column" : "Columna",
    "Constrain proportions" : "Restringir proporciones",
    "Contrast" : "Contraste",
    "Copy row" : "Copiar fila",
    "Copy" : "Copiar",
    "Could not find the specified string." : "No se encuentra la cadena de texto especificada",
    "Crop" : "Recortar",
    "Custom color" : "Color personalizado",
    "Custom..." : "Personalizar...",
    "Cut row" : "Cortar fila",
    "Cut" : "Cortar",
    "Decrease indent" : "Disminuir sangr\u00eda",
    "Default" : "Por defecto",
    "Delete column" : "Eliminar columna",
    "Delete row" : "Eliminar fila",
    "Delete table" : "Eliminar tabla",
    "Description" : "Descripci\u00f3n",
    "Dimensions" : "Dimensiones",
    "Disc" : "Disco",
    "Div" : "Capa",
    "Document properties" : "Propiedades del documento",
    "Edit image" : "Editar imagen",
    "Edit" : "Editar",
    "Embed" : "Incrustado",
    "Emoticons" : "Emoticones",
    "Encoding" : "Codificaci\u00f3n",
    "File" : "Archivo",
    "Find and replace" : "Buscar y reemplazar",
    "Find" : "Buscar",
    "Finish" : "Finalizar",
    "Flip horizontally" : "Invertir horizontalmente",
    "Flip vertically" : "Invertir verticalmente",
    "Font Family" : "Fuentes",
    "Font Sizes" : "Tama\u00f1o de Fuente",
    "Footer" : "Pie de p\u00e1gina",
    "Format" : "Formato",
    "Formats" : "Formatos",
    "Fullscreen" : "Pantalla Completa",
    "Gamma" : "Gamma",
    "General" : "General",
    "G" : "G",
    "H Align" : "Alineamiento Horizontal",
    "Header cell" : "Celda de la cebecera",
    "Header 1" : "Encabezado 1",
    "Header 2" : "Encabezado 2",
    "Header 3" : "Encabezado 3",
    "Header 4" : "Encabezado 4",
    "Header 5" : "Encabezado 5",
    "Header 6" : "Encabezado 6",
    "Header" : "Cabecera",
    "Headers" : "Encabezados",
    "Heading 1" : "Encabezado 1",
    "Heading 2" : "Encabezado 2",
    "Heading 3" : "Encabezado 3",
    "Heading 4" : "Encabezado 4",
    "Heading 5" : "Encabezado 5",
    "Heading 6" : "Encabezado 6",
    "Headings" : "Encabezados",
    "Height" : "Alto",
    "Horizontal line" : "L\u00ednea Horizontal",
    "Horizontal space" : "Espacio Horizontal",
    "Ignore all" : "Ignorar todos",
    "Ignore" : "Ignorar",
    "Image description" : "Descripci\u00f3n de la imagen",
    "Image options" : "Opciones de imagen",
    "Increase indent" : "Incrementar sangr\u00eda",
    "Inline" : "En l\u00ednea",
    "Insert column after" : "Insertar columna despu\u00e9s",
    "Insert column before" : "Insertar columna antes",
    "Insert date\/time" : "Insertar Fecha\/hora",
    "Insert image" : "Insertar Imagen",
    "Insert link" : "Insertar enlace",
    "Insert row after" : "Insertar fila despu\u00e9s",
    "Insert row before" : "Insertar fila antes",
    "Insert table" : "Insertar tabla",
    "Insert template" : "Insertar plantilla",
    "Insert video" : "Insertar video",
    "Insert\/edit image" : "Insertar\/Editar Imagen",
    "Insert\/edit link" : "Insertar\/editar enlace",
    "Insert\/edit video" : "Insertar\/editar video",
    "Insert" : "Insertar",
    "Invert" : "Invertir",
    "Italic" : "It\u00e1lica",
    "Justify" : "Justificar",
    "Keywords" : "Palabras clave",
    "Left to right" : "De izquierda a derecha",
    "Left" : "Izquierda",
    "Lower Alpha" : "Inferior Alfa",
    "Lower Greek" : "Inferior Griega",
    "Lower Roman" : "Inferior Romana",
    "Match case" : "Coincidencia exacta",
    "Merge cells" : "Combinar celdas",
    "Middle" : "Centro",
    "Name" : "Nombre",
    "New document" : "Nuevo documento",
    "New window" : "Nueva ventana",
    "Next" : "Siguiente",
    "No color" : "Sin color",
    "Nonbreaking space" : "Espacio fijo",
    "None" : "Ninguno",
    "Numbered list" : "Lista numerada",
    "Ok" : "Ok",
    "Orientation" : "Orientaci\u00f3n",
    "Page break" : "Salto de p\u00e1gina",
    "Paragraph" : "P\u00e1rrafo",
    "Paste as text" : "Pegar como texto",
    "Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off." : "Pegar est\u00e1 ahora en modo de texto plano. El contenido no ser\u00e1 pegado como texto plano hasta que desactives esta opci\u00f3n.",
    "Paste row after" : "Pegar la fila despu\u00e9s",
    "Paste row before" : "Pegar la fila antes",
    "Paste your embed code below:" : "Pega tu c\u00f3digo embebido debajo",
    "Paste" : "Pegar",
    "Poster" : "Miniatura",
    "Pre" : "Pre",
    "Prev" : "Anterior",
    "Preview" : "Previsualizaci\u00f3n",
    "Print" : "Imprimir",
    "Redo" : "Rehacer",
    "Remove link" : "Quitar enlace",
    "Replace all" : "Reemplazar todo",
    "Replace with" : "Reemplazar con",
    "Replace" : "Reemplazar",
    "Resize" : "Redimensionar",
    "Restore last draft" : "Restaurar el \u00faltimo borrador",
    "Rich Text Area. Press ALT-F9 for menu. Press ALT-F10 for toolbar. Press ALT-0 for help" : "\u00c1rea de texto enriquecido. Pulse ALT-F9 para el menu. Pulse ALT-F10 para la barra de herramientas. Pulse ALT-0 para ayuda",
    "Right to left" : "De derecha a izquierda",
    "Right" : "Derecha",
    "Robots" : "Robots",
    "Rotate clockwise" : "Girar a la derecha",
    "Rotate counterclockwise" : "Girar a la izquierda",
    "Row group" : "Grupo de filas",
    "Row properties" : "Propiedades de la fila",
    "Row type" : "Tipo de fila",
    "Row" : "Fila",
    "Rows" : "Filas",
    "R" : "R",
    "Save" : "Guardar",
    "Scope" : "\u00c1mbito",
    "Select all" : "Seleccionar todo",
    "Sharpen" : "Forma",
    "Show blocks" : "Mostrar bloques",
    "Show invisible characters" : "Mostrar caracteres invisibles",
    "Source code" : "C\u00f3digo Fuente",
    "Source" : "Fuente",
    "Special character" : "Car\u00e1cter Especial",
    "Spellcheck" : "Corrector ortogr\u00e1fico",
    "Split cell" : "Dividir celdas",
    "Square" : "Cuadrado",
    "Strikethrough" : "Tachado",
    "Style" : "Estilo",
    "Subscript" : "Sub\u00edndice",
    "Superscript" : "Super\u00edndice",
    "Table properties" : "Propiedades de la tabla",
    "Table" : "Tabla",
    "Target" : "Destino",
    "Templates" : "Plantillas",
    "Text color" : "Color del texto",
    "Text to display" : "Texto para mostrar",
    "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?" : "El enlace que has introducido no parece ser una direcci\u00f3n de correo electr\u00f3nico. Quieres a\u00f1adir el prefijo necesario mailto: ?",
    "The URL you entered seems to be an external link. Do you want to add the required http:\/\/ prefix?" : "El enlace que has introducido no parece ser una enlace externo. Quieres a\u00f1adir el prefijo necesario http:\/\/ ?",
    "Title" : "T\u00edtulo",
    "Tools" : "Herramientas",
    "Top" : "Arriba",
    "Underline" : "Subrayado",
    "Undo" : "Deshacer",
    "Upper Alpha" : "Superior Alfa",
    "Upper Roman" : "Superior Romana",
    "Url" : "URL",
    "V Align" : "Alineamiento Vertical",
    "Vertical space" : "Espacio Vertical",
    "View" : "Ver",
    "Visual aids" : "Ayudas Visuales",
    "Whole words" : "Palabras completas",
    "Width" : "Ancho",
    "Words: {0}" : "Palabras: {0}",
    "You have unsaved changes are you sure you want to navigate away?" : "Tiene cambios sin guardar. \u00bfEst\u00e1 seguro de que quiere salir?",
    "Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X\/C\/V keyboard shortcuts instead." : "Tu navegador no soporta el acceso directo al portapapeles. Por favor, utiliza los atajos de teclados Ctrl+X\/C\/V.",
    "Zoom in" : "Acercar",
    "Zoom out" : "Alejar"
});